### ISSUE TITLE
Consola

### ISSUE THREAD

**Issue by Nidev-lab** [Fsalasgit/LAM-music-store#78]
## Proceso

1. Ingrese a la pagina.
2. Mire unos productos.

## Resultado esperado

• Que no se muestre informacion por la consola.

## Resultado actual

• Al ingresar a un producto se muestra informacion por consola.

## Captura

![image](https://github.com/Fsalasgit/LAM-music-store/assets/53904695/10558097-c82f-42f2-addc-bbcf13adcc0e)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by brunobusnelli** [comment]
Buenas!
Ya esta resuelto y se da el resultado esperado.
Muchas Gracias
