### ISSUE TITLE
Sobre nosotros

### ISSUE THREAD

**Issue by Nidev-lab** [Fsalasgit/LAM-music-store#79]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que las imágenes se muestren correctamente. 

## Resultado actual

• Las imagenes no cargan y se muestra errores por consola.

## Captura

![image](https://github.com/Fsalasgit/LAM-music-store/assets/53904695/2e7711e7-9e95-449c-800f-a490436f3fd2)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by brunobusnelli** [comment]
Buenas!
Ya esta resuelto y se da el resultado esperado.
Muchas Gracias
